# Generated by Django 4.0.4 on 2024-01-21 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='presence',
            field=models.CharField(choices=[('PR', 'Present'), ('UN', 'Unexcused absence'), ('EX', 'Excused absence')], max_length=10),
        ),
    ]
