# Generated by Django 4.0.4 on 2024-01-21 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_remove_attendance_presence'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='presence',
            field=models.CharField(blank=True, choices=[('PR', 'Present'), ('UN', 'Unexcused absence'), ('EX', 'Excused absence')], max_length=2),
        ),
    ]
